# Trigger redeploy

name = "chips-gifs-api"
compatibility_date = "2026-02-10"

[build]
command = "npm install"
pages_build_output_dir = "."

[vars]
SUPABASE_URL = ""
SUPABASE_SERVICE_ROLE_KEY = ""
IPINFO_TOKEN = ""

[[r2_buckets]]
binding = "CHIPS_GIFS"
bucket_name = "chips-gifs"
preview_bucket_name = "chips-gifs"
